#!/bin/sh

set -e

poetry install

for script in mplocal \
              mplocal-monolithic \
              mplocal-separate-payload \
              mpglobal \
              mpglobal-monolithic \
              mpglobal-separate-payload
do
    printf "\n\n%s:\n\n" "$script"
    poetry run "$script"
done
