#!/bin/sh
#
# Shell script to run all the experiment scripts and show the results.
#
# Usage:
#
#    ./runall
#
# This should be run from the top-level directory of the repository, i.e., the
# directory that contains it and pyproject.toml (among other files).

set -e

poetry install
printf '\n'
poetry env list
printf '\n'
poetry run python -V

for script in mplocal \
              mplocal-monolithic \
              mplocal-separate-payload \
              mpglobal \
              mpglobal-monolithic \
              mpglobal-separate-payload
do
    printf "\n\n%s:\n\n" "$script"
    poetry run "$script"
done
