name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  ruff-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install development dependencies
      run: poetry install --no-root

    - name: Ruff (general)
      run: poetry run ruff check .

  ruff-format:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install development dependencies
      run: poetry install --no-root

    - name: Ruff (formatting)
      run: poetry run ruff format --check .

  isort:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install development dependencies
      run: poetry install --no-root

    - name: isort (imports)
      run: poetry run isort --check .
