name: Typecheck

on: [push, pull_request, workflow_dispatch]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install development dependencies
      run: poetry install --no-root

    - name: Typecheck with mypy
      run: poetry run mypy .

  pyright:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install development dependencies
      run: poetry install --no-root

    - name: Typecheck with pyright
      run: poetry run pyright .
